---
title: "homework 1"
Author: "Anchalya Bala"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Question 1
```{r}
#**Question 1: Create a new vector in R with the data for each strain.**
#transgenic strain a: 
straina = c(0.17,0.20,0.13,0.20,0.24,0.25,0.15,0.21,0.21)
#transgenic strain b: 
strainb = c(0.47,0.21,0.34,0.32,0.33,0.29,0.18,0.20,0.25)
#common strain: 
commonstrain = c(0.44,0.33,0.37,0.33,0.31,0.27,0.22,0.30,0.28)
```

#Question 2
```{r}
#**Question 2:What is the difference between the means of the two
#transgenic strains?**
print("the mean of straina:") 
mean(straina)
print("the mean of strainb:")
mean(strainb)
(mean(straina)+ mean(strainb))/2
```

#Question 3
```{r}
#**Question 3: What is the difference between the means of the common
#strain and transgenic strain A?**
print("the mean of commonstrain:")
mean(commonstrain)
print("the mean of straina")
mean(straina)
print("difference means of the common strain and transgenic strain A")
(mean(commonstrain)+ mean(straina))/2
```

#Question 4
```{r}
#**Question 4:Create a histogram of the hydrogen peroxide concentrations in
#the common strain.**
hist(commonstrain)
```

#Question 5

```{r}
#**Question 5:Enter each column as a vector in R, and collect these into a
#single data frame. Name the hydrogen peroxide column
#‘Peroxide’ and the fungal growth rate column ‘Growth.rate’.**
peroxide = c(0.27,0.21,0.34,0.32,0.24,0.29,0.18,0.20,0.29)
growth.rate = c(1.79,1.01,1.71,1.89,1.41,1.15,1.13,1.20,1.10)
```

#Question 6
```{r}
#**Question 6:Create a scatter plot of fungal growth rate versus peroxide
#concentration from the newly created data frame. Make sure to 
#label the plot properly (label the axes and make sure to provide the measurement units).
plot(peroxide,growth.rate,xlab='Hydrogen peroxide concentrations (µmoles/g)',ylab='Fungal,growth rate (cm/day)',main='Concentration of Hydrogen Peroxide in Leaf Tissues vs. Growth Rate of Fungus at the Leaf Edge of the Commonstrain')
```

#Question 7
```{r}
#**Question 7: How does the growth rate of the fungus change with increasing
#levels of hydrogen peroxide, and does this agree or disagree with the hypothesis?**

my.reg=lm(growth.rate~peroxide)
summary(my.reg)

plot(peroxide,growth.rate,xlab='Hydrogen peroxide concentrations (µmoles/g)',ylab='Fungal,growth rate (cm/day)',main='Concentration of Hydrogen Peroxide in Leaf Tissues vs. Growth Rate of Fungus at the Leaf Edge of the Commonstrain')
abline(my.reg)
#there is a correlation between fungus change and levels of hydrogen peroxide as seen by the line of regression. There is an increase, but I feel that it is not very statistically relevent 
```

#Question 8
```{r}
#**Question 8: Re-create this table in Excel and save as a comma separated
#values file. Read the data into R using the read.csv function.**
my.dat=read.csv(file.choose())
```

#Question 9
```{r}
#**Question 9:Use the table function to create a contingency table showing
#the number of aborted and successful nesting attempts for each species.**
hw1.3=table(my.dat)
hw1.3
```

#Question 10
```{r}
#**Question 10:Make and label a grouped barplot that represents the nesting
#patterns for all three turtle species. Color the bars for successful green and #the bars for aborted red. Make sure to label the axes.**

barplot(hw1.3,col= c('red', 'green'),main='Nesting Patterns for Three
Species of Marine Turtle Over a One Month Span',xlab='Species',ylab='Sucess rate')
```

#Question 11
```{r}
#**Question 11: Determine the mean and standard deviation of successful
#nesting events among all marine turtles.**
hw1.3
mean(hw1.3[2,])
sd(hw1.3[2,])
```
#Question 12
```{r}
#**Question 12: Calculate the proportion of failed nesting attempts for each
#species. Based on this, which species would you choose as needing the greatest #conservation effort?**
hw1.3
mean(hw1.3[1,])
sd(hw1.3[1,])
#the species that I would choose as needing the greatest conservation effort is hawksbill
```
#Question 13
```{r}
#**Question 13: Enter data into Excel and import the file to R.**
my.dat=read.csv(file.choose())
```
#Question 14
```{r}
#**Question 14: Create a boxplot comparing different turtle species and the
#number of eggs found in the nest. Don’t forget to label your axes.**
hw1.4=table(my.dat)
hw1.4=boxplot(my.dat,xlab='Turtle Species',ylab='Number of Eggs',main='Turtle Species VS. Number of Eggs Found in The Nest')

```
#Question 15
```{r}
#**Question 15: Create a scatter plot of the number of Leatherback turtle eggs
#(y-axis) against the number of Hawksbill turtle eggs (x-axis) across all beach #sections.**
hw1.4=table(my.dat)
plot(my.dat$Hawksbill,my.dat$Leatherback,xlab='Hawksbill Turtle Eggs',ylab='Leatherback Turtle Eggs',main='Hawksbill Turtle Eggs VS Leatherback Turtle Eggs Across All Beach Sections')
```

