---
title: "hw2"
author: "Anchalya"
date: "18/01/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

#Scenario 1
```{r}
#A)State the null and alternative hypotheses? 
#HO: There is no difference between the two groupsdent
#HA: There is a difference between the two groups
```

```{r}
#B)Create a histogram of the data. 
data <- read.csv('hw2.1.csv')
data$VillageCode <- as.numeric(data$VillageCode)
data
hist(data$catch1,
     main="Histogram for 2009 Catch", 
     xlab="Catch Range", 
     border="blue", 
     col="pink",
     las=1, 
     breaks=5)
hist(data$catch2,
main="Histogram for 2010 Catch", 
     xlab="Catch Range", 
     border="blue", 
     col="purple",
     las=1, 
     breaks=5)
```

```{r}
#C)Explain what type of test should be used to test the hypothesis.
#The type of test that should be used to test the hypothesis is a paired two #sample t-test for independence because because we are trying to determine if #there is a difference betweeb the two catch groups. Before and after studies #commonly use paired t-tests to show how a specific population changes with the #application of some treatment, in thise case it is the oilspill. 
```

```{r}
#D)Run the appropriate test, and display the summary output
data
catch1 = data$catch1
catch2 = data$catch2
t.test(catch1, catch2, paired=TRUE, conf.level=0.95)

```

```{r}
#E)Explicitly state the critical and observed value of the test statistic.
qt(0.95,13)
#the critcal value is 1.770933 and the observed tvalue is 6.3808
```

```{r}
#F) Indicate what conclusion you would draw from the hypothesis test.
#because the pvalue is less than 0.05, we will need to reject the null #hypothesis. therefore, There is a difference between the two groups.  
```

Scenario 2
```{r}
#A)State the null and alternative hypotheses? 
#HO: The total number of phosphorous in Lake Erie is not less the maximum of #15μg/L
#HA: The total number of phosphorous in Lake Erie is less the maximum of #15μg/L
```

```{r}
#B)Create a histogram of the data. 
data2 <- read.csv('hw2.2.csv') 
hist(data2$TotalPhos,
     main="Histogram of Phosphorous Levels (μg/L) at Lake Erie",
     xlab="Total Phosphorous (μg/L)",
     border="blue",
     col="orange",
     las=1,
     breaks=5)
    
```

```{r}
#c) Explain what type of test should be used to test the hypothesis.
#the type of test that should be used is a one sample t-test. A one-sample #t-test compares the mean of an observed set of data to a known value. This
#test assumes that the observed data is normally distributed. 
```

```{r}
#d) Run the appropriate test, and display the summary output.
data2
t.test(data2$TotalPhos, mu=15)
```

```{r}
#E)Explicitly state the critical and observed value of the test statistic.
qt(0.975,9)
#the critcal value is 2.262157 and the observed t-value is 1.8462
```

```{r}
#F) Indicate what conclusion you would draw from the hypothesis test.
#since the calculated tvalue is less than the critical value, we accept the #null hypothesis. This makes sense because the total number of phosphorus level #is not less than the max of 15μg/L
```

Scenario 3
```{r}
#a) State the null and alternative hypotheses?
#HO: There is no difference between the two groups
#HA: There is a difference between the two groups
```

```{r}
#b) Create a histogram of the data.
stinky =read.csv('stinkyfile.csv') 
hist(stinky$carnivorous,
     main="Histogram of carnivorous",
     xlab="carnivorous",
     border="red",
     col="blue",
     las=1,
     breaks=5)
hist(stinky$vegetarian,
     main="Histogram of vegetarian",
     xlab="vegetarian",
     border="blue",
     col="orange",
     las=1,
     breaks=5)
```

```{r}
#C)Explain what type of test should be used to test the hypothesis.
#the type of test I would use is two sample t-tests. This test was used to #evaluate whether two populations have different means, and are an invaluable #tool for differentiating between the outcomes of two trials. 
```

```{r}
#d) Run the appropriate test, and display the summary output.
 t.test(stinky$carnivorous, stinky$vegetarian)
```

```{r}
#e) Explicitly state the critical and observed value of the test statistic.
qt(0.95,27.862)
#the critical value is 1.701419 and the observed t-value is 12.237
```

```{r}
#f) Indicate what conclusion you would draw from the hypothesis test.
#From the summary, p<0.05, so we reject the null hypothesis and conclude that vegetarion diet differes from the carnivorous diet in terms of growth rate of the farmed salmon.
```

Scenario 4
```{r}
#a) State the null and alternative hypotheses? 
#HO: There is no interaction between symptoms and the
#trophic level of the individual in question
#HA: There is a an interaction between symptoms and the
#trophic level of the individual in question
```

```{r}
#b) Create a histogram of the data. 
troph=c(133,100,17,250)
toppredator=c(4,61,35,100)
dat=data.frame('C'=troph,'NC'=toppredator)
dat
hist(dat$C)
hist(dat$NC)
```

```{r}
#c) Explain what type of test should be used to test the hypothesis.
#The tpe of test that should be used to test the hypothesis is Chi-squared #test. A Chi-squared test is used to test for independence among categorical #variables. 
```

```{r}
#d) Run the appropriate test, and display the summary output.
chisq.test(dat)
```

```{r}
#e) Explicitly state the critical and observed value of the test statistic.
qchisq(0.95,3)
#the Critical value is 7.814728
#The observed value is x-squared=89.253
```

```{r}
#f) Indicate what conclusion you would draw from the hypothesis test.
#because the pvalue is less than 0.05, the null hypthesis will be rejected. Therefore, here is a an interaction between symptoms and the
#trophic level of the individual in question
```

